# Generated by Django 4.2.30 on 2026-08-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#49B64E', max_length=7, verbose_name='Цвет'),
        ),
    ]
