# Generated by Django 4.2.30 on 2026-08-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'Корзины покупок'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
