# Теги
TAG_NAME_MAX_LENGTH = 32
SLUG_MAX_LENGTH = 32

# Ингредиенты
INGREDIENT_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64

# Рецепты
RECIPE_NAME_MAX_LENGTH = 256
MAX_COOKING_TIME = 32767
# Ингредиенты в рецепте
MAX_INGREDIENT_AMOUNT = 32767
